require("../../components/components.js")
import './index.scss'
import './assets/logo.svg'
import './assets/phoneIcon.svg'
import './assets/clock.svg'
import './assets/envelope.svg'
import './assets/vk.svg'
import './assets/yt.svg'
import './assets/wa.svg'
import './assets/arrow.svg'